FROM {{ .BaseImage }}

MAINTAINER hcf@hpe.com

# Install prerequisites
RUN useradd -m --comment 'hcf user' vcap && groupadd --system admin && usermod -G admin,adm,audio,cdrom,dialout,floppy,video,dip,plugdev vcap

# Install monit

RUN apt-get update && apt-get install monit runit curl software-properties-common -y
ADD monitrc.erb /opt/hcf/monitrc.erb

# Setup syslog

RUN add-apt-repository ppa:adiscon/v8-stable && apt-get update && apt-get install rsyslog rsyslog-relp rsyslog-mmjsonparse rsyslog-gnutls -y

# Enable resolvconf updates
RUN resolvconf --enable-updates

# Setup default locale and timezone
RUN echo 'LANG="en_US.UTF-8"' > /etc/default/locale
RUN echo 'UTC' > /etc/timezone
RUN DEBIAN_FRONTEND=noninteractive locale-gen en_US.UTF-8 && dpkg-reconfigure -fnoninteractive -pcritical tzdata && dpkg-reconfigure locales

# Install configgin

ADD configgin /opt/hcf/configgin/
