FROM {{ index . "base_image" }}

{{ if not .dev }}
MAINTAINER cloudfoundry@suse.example
{{ end }}

LABEL "role"="{{ .role.Name }}"

ADD root /

RUN chmod +x /opt/fissile/run.sh
ENTRYPOINT ["/usr/bin/dumb-init", "/opt/fissile/run.sh"]
