FROM {{ .BaseImage }}

MAINTAINER hcf@hpe.com

# Install prerequisites

# Install monit

RUN apt-get update && apt-get install monit -y
ADD monitrc.erb /opt/hcf/monitrc.erb

# Install configgin

ADD configgin /opt/configgin/
