package cmd

import (
	"github.com/SUSE/fissile/model"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var (
	flagBuildKubeOutputDir       string
	flagBuildKubeDefaultEnvFiles []string
	flagBuildKubeUseMemoryLimits bool
	flagBuildKubeCreateHelmChart bool
	flagBuildKubeChartFilename   string
)

// buildKubeCmd represents the kube command
var buildKubeCmd = &cobra.Command{
	Use:   "kube",
	Short: "Creates Kubernetes configuration files.",
	Long:  ``,
	RunE: func(cmd *cobra.Command, args []string) error {

		flagBuildKubeOutputDir = viper.GetString("output-dir")
		flagBuildKubeDefaultEnvFiles = splitNonEmpty(viper.GetString("defaults-file"), ",")
		flagBuildKubeUseMemoryLimits = viper.GetBool("use-memory-limits")
		flagBuildKubeCreateHelmChart = viper.GetBool("create-helm-chart")
		flagBuildKubeChartFilename = viper.GetString("chart-file")

		err := fissile.LoadReleases(
			flagRelease,
			flagReleaseName,
			flagReleaseVersion,
			flagCacheDir,
		)
		if err != nil {
			return err
		}

		opinions, err := model.NewOpinions(
			flagLightOpinions,
			flagDarkOpinions,
		)
		if err != nil {
			return err
		}

		return fissile.GenerateKube(
			flagRoleManifest,
			flagBuildKubeOutputDir,
			flagRepository,
			flagDockerRegistry,
			flagDockerOrganization,
			fissile.Version,
			flagBuildKubeDefaultEnvFiles,
			flagBuildKubeUseMemoryLimits,
			flagBuildKubeCreateHelmChart,
			flagBuildKubeChartFilename,
			opinions,
		)
	},
}

func init() {
	buildCmd.AddCommand(buildKubeCmd)

	buildKubeCmd.PersistentFlags().StringP(
		"output-dir",
		"",
		".",
		"Kubernetes configuration files will be written to this directory",
	)

	buildKubeCmd.PersistentFlags().StringP(
		"defaults-file",
		"D",
		"",
		"Env files that contain defaults for the parameters generated by kube",
	)

	buildKubeCmd.PersistentFlags().BoolP(
		"use-memory-limits",
		"",
		true,
		"Include memory limits when generating kube configurations",
	)

	buildKubeCmd.PersistentFlags().BoolP(
		"create-helm-chart",
		"",
		false,
		"Write kube configuration as a helm chart",
	)

	buildKubeCmd.PersistentFlags().StringP(
		"chart-file",
		"",
		"Chart.yaml",
		"Chart.yaml file that will be copied into the helm chart",
	)

	viper.BindPFlags(buildKubeCmd.PersistentFlags())
}
