#!/bin/sh

set -o errexit

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

set +o errexit

. ${GIT_ROOT}/make/include/versioning

set -o errexit

set -o nounset

${GIT_ROOT}/make/bindata
go build -ldflags="-X main.version=${APP_VERSION}"
