#!/bin/sh

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

rm -rf ${GIT_ROOT}/build
rm -f ${GIT_ROOT}/fissile
rm -f ${GIT_ROOT}/scripts/{compilation/compilation,dockerfiles/dockerfiles,templates/transformations}.go
