#!/bin/sh

set -o errexit

. make/include/colors.sh

printf "%b==> Formatting %b\n" "${OK_COLOR}" "${ERROR_COLOR}"

ISSUES=$(mktemp)

trap "cat ${ISSUES} ; rm -f ${ISSUES}" EXIT

go list -f '{{ .Dir }}' ./... | sed '/fissile[/]scripts/d ; /\/vendor\//d' | while read DIR; do
    goimports -d -e "${DIR}"/*.go >> "${ISSUES}"
done

printf "%b" "${NO_COLOR}"

test ! -s "${ISSUES}"
