#!/bin/sh

set -o errexit

export GOPATH=$(godep path):${GOPATH}

ISSUES=$(mktemp)

trap "rm -f ${ISSUES}" HUP INT TERM

go list -f '{{ .Dir }}' ./... | sed '/fissile[/]scripts/d' | while read DIR; do
    goimports -d -e ${DIR}/*.go | tee -a ${ISSUES}
done

ISSUE_COUNT=$(cat ${ISSUES} | wc -l)

rm -f ${ISSUES}

test ${ISSUE_COUNT} -eq 0
