#!/bin/sh

set -o errexit

ISSUES=$(mktemp)

trap "rm -f '${ISSUES}'" EXIT

go list -f '{{ .Dir }}' ./... | sed '/fissile[/]scripts/d ; /\/vendor\//d ' | while read DIR; do
    golint $(ls "${DIR}"/*.go | grep -v _generated.go) | tee -a "${ISSUES}"
done

# Check that the issues list is empty. (We fail with an error due to errexit)
test ! -s "${ISSUES}"
