#!/bin/sh

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. ${GIT_ROOT}/make/include/versioning

set -o errexit -o nounset

GOOS=${GOOS:-$(go env GOOS)}
GOARCH=${GOARCH:-$(go env GOARCH)}

${GIT_ROOT}/make/build
tar czf ${APP_VERSION}-${GOOS}.${GOARCH}.tgz fissile
