#!/bin/sh

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
SRC=$(basename $GIT_ROOT)

. ${GIT_ROOT}/make/include/versioning
echo ${ARTIFACT_NAME},${GIT_BRANCH},${GIT_DESCRIBE} > .version

pushd ..
tar --exclude=.git -cJvf fissile-${ARTIFACT_VERSION}.tar.xz $SRC
popd
