#!/bin/sh

set -o errexit

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

${GIT_ROOT}/make/bindata
${GIT_ROOT}/make/docker-deps

. make/include/colors.sh

printf "%b==> Testing %b\n" "${OK_COLOR}" "${NO_COLOR}"

go generate ./docker/ # for mocks
go test -race -cover $(go list -f '{{ .ImportPath }}' ./... | sed '/fissile[/]scripts/d ; /\/vendor\//d')
